name: Dependabot auto-merge
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - id: automerge
        name: automerge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_DELETE_BRANCH: true
          MERGE_FILTER_AUTHOR: dependabot[bot]
          MERGE_LABELS: ''
          MERGE_METHOD: squash