name: Create new release v2
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 */3 *"
    
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
          clean: true

      - id: latestRelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Get Next Version
        id: nextSemver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: master
          patchList: build, fix, bugfix, perf, refactor, test, tests
          fallbackTag: ${{ steps.latestRelease.outputs.release }}

      - name: Update release in gradle.properties
        run: |
          sed -i "s/^version.*/version=${{ steps.nextSemver.outputs.nextStrict }}/g" gradle.properties

      - name: Publish package
        run: ./gradlew publish
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        id: create-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.nextSemver.outputs.nextStrict }}
          name: quartz-mongodb ${{ steps.nextSemver.outputs.next }}
          draft: false
          body: |
            Maven Usage:
              ```
              <dependency>
                <groupId>io.github.avi-sanwal</groupId>
                <artifactId>quartz-mongodb</artifactId>
                <version>${{ steps.nextSemver.outputs.nextStrict }}</version>
              </dependency>
              ```
            Gradle Usage:
              `implementation("io.github.avi-sanwal:quartz-mongodb:${{ steps.nextSemver.outputs.nextStrict }}")`
          generate_release_notes: true
          files: |
            build/libs/quartz-mongodb-${{ steps.nextSemver.outputs.nextStrict }}.jar
            build/libs/quartz-mongodb-${{ steps.nextSemver.outputs.nextStrict }}-sources.jar
            build/libs/quartz-mongodb-${{ steps.nextSemver.outputs.nextStrict }}-javadoc.jar
